# Reversing Rows and Columns

In numpy array we use the [] operator with following syntax,

arr[start:end:stepsize]

It will basically select the elements from start to end-1 with step size as stepsize.

In [1]:
import numpy as np

In [2]:
a=[1,2,3,4,5,6,7,8];
b=np.array(a)

In [3]:
b

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
b.shape

(8,)

# Now the convension is , if we don't mension start and stop & give 1 as stepsize , it will go from beginning to end

# & if we mension -1 as stepsize , it will go from end to beginning 

So simple code to reverse the array--

In [26]:
m=b[::-1];#As we are not specifying the start and stop index, Python will reverse this as we have given stepsize -1
m

array([8, 7, 6, 5, 4, 3, 2, 1])

# Reversing rows of 2D Array

In [28]:
a=[[1,2,3,4],[5,6,7,8]];
ms=np.array(a)

In [29]:
ms

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

To reverse anything the strategy is ::-1 
        
So case 1:
    
Reversing rows keeping columns in same order

[::-1,:]

Case2:
    
Reversing columns keeping rows same order--

[:,::-1]

Case3:
    
Reversing both rows and columns--

[::-1,::-1]

In [33]:
ms

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
ms[:,::-1]#Reversing the columns keeping rows order same

array([[4, 3, 2, 1],
       [8, 7, 6, 5]])

In [32]:
ms[::-1,:]#Reversing the rows keeping columns order same

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

In [34]:
ms[::-1,::-1]#Reversing both rows and columsn

array([[8, 7, 6, 5],
       [4, 3, 2, 1]])

# VVVVI

# Getting the rows and columsn separately of a 2D matrix

In [37]:
ms.shape# We are getiing the shape as tuple form , so we can unpack that to get rows and columsn in different variables

(2, 4)

In [38]:
(rows,columns)=ms.shape;
print(rows);
print(columns);

2
4


# Specific Element Extrcation 

In [40]:
ms

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Rule:-
-----
Almost same like MATLAB , just it's 0 based indexing & [] , not ()

In [42]:
#First Row 
ms[0,:]

array([1, 2, 3, 4])

In [44]:
#Second Row
ms[1,:]

array([5, 6, 7, 8])

In [46]:
#3rd Column
ms[:,2]

array([3, 7])

In [47]:
#First 3 columns
ms[:,0:3:1]

array([[1, 2, 3],
       [5, 6, 7]])