# Loading Library

In [1]:
import numpy as np

In [2]:
a=[1,2,3,4,5,6];
b=np.array(a);#List to array conversion

In [3]:
a

[1, 2, 3, 4, 5, 6]

In [4]:
type(a)

list

In [5]:
b

array([1, 2, 3, 4, 5, 6])

In [6]:
type(b)

numpy.ndarray

# Difference between Array and List or Why we require Array?

To perform vector operation like MATLAB, this is required

In [7]:
a+1# lists cannot directly handle math operations.

TypeError: can only concatenate list (not "int") to list

In [25]:
[1,2,3,4]+[5,6,7,8,9,10]#Like this List concatenation is performed , that's why above error is coming

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [26]:
b+1#Vector Operation

array([2, 3, 4, 5, 6, 7])

# 2d Array

# We can create 2d Array from 2d List --

In [9]:
am=[[1,2,3,4],[5,6,7,8]];     
bm=np.array(am)

In [10]:
bm

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
#Converting Integer List to float array
cm=np.array(am,dtype='float');
print(cm)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [12]:
cm.dtype

dtype('float64')

In [13]:
type(cm)

numpy.ndarray

# The difference between type and dtype

The type of a NumPy array is numpy.ndarray; 
this is just the type of Python object it is (similar to how type("hello") is str for example).

dtype just defines how bytes in memory will be interpreted by a scalar (i.e. a single number) or 
an array and the way in which the bytes will be treated (e.g. int/float). 


# For that reason you don't change the type of an array or scalar, just its dtype.

In [ ]:
#Convert this Float array again to Integer
mk=cm.astype('int');#method is used to cast a object to a specified dtype
(mk)

# dtype and astype --when to use what?

one list to one array of specific datatype--dtype


one array to another array of specific datatype--astype

In [15]:
#Converting Integer List to boolean array
cms=np.array(am,dtype='bool');
cms#If 0 then false , else true

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [16]:
am=[[1,2,3,0],[5,6,7,8]];
bm=np.array(am,dtype='bool');
bm

array([[ True,  True,  True, False],
       [ True,  True,  True,  True]])

In [17]:
lop=bm.astype('int');
lop

array([[1, 1, 1, 0],
       [1, 1, 1, 1]])

In [18]:
lo=[1,2,3,"Hello",5.4];
bm=np.array(lo,dtype=object);
bm

array([1, 2, 3, 'Hello', 5.4], dtype=object)

In [19]:
mkls=[1,2,3,4];
kla=np.array(mkls);
los=kla.tolist();
type(los)

list

In [20]:
am=[[1,2,3,4],[5,6,7,8]];
bm=np.array(am)

In [27]:
bm.shape#Shape means figure or what form it has , so it will return number of rows*number of columns

(2, 4)

In [22]:
bm.size#Size is representatiove of overall volume , so returns total number of elements

8

In [23]:
bm.dtype#how bytes in memory will be interpreted as mentinoed earlier

dtype('int32')

In [24]:
bm.ndim#Number of Dimensions of the array

2