# Reshaping Array

In [1]:
import numpy as np

In [2]:
a=[[1,2,3,4],[8,9,10,11]];
b=np.array(a)

In [6]:
b

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [5]:
b.shape

(2, 4)

#  Numpy and MATLAB differ in their default way of getting elements when doing a reshape.

# The numpy stores data in row major order where MATLAB is Column Major

In [7]:
c=b.reshape(4,2);
c

array([[ 1,  2],
       [ 3,  4],
       [ 8,  9],
       [10, 11]])

In [9]:
c=b.reshape(8,1);
c

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 8],
       [ 9],
       [10],
       [11]])

In [10]:
c=b.reshape(1,8);
c

array([[ 1,  2,  3,  4,  8,  9, 10, 11]])

## Note

# The total number of elements before and after reshaping should be same

In [12]:
c=b.reshape(4,4)#We will be getting error is total number of elements before and after reshaping are not same

ValueError: cannot reshape array of size 8 into shape (4,4)

# Flatten Array

Deafult flatten in row-major order

In [14]:
b

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [15]:
b.flatten()

array([ 1,  2,  3,  4,  8,  9, 10, 11])