# Creating Different Matrix
## Note(So that we won't be confuse):
## We are creating array , so it will be inside np package 

# Creating Zero Matrix

In [2]:
import numpy as np

In [5]:
a=np.zeros([2,3]);
a

array([[0., 0., 0.],
       [0., 0., 0.]])

# Creating One Matrix

In [7]:
b=np.ones([2,5])
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Linspace same like MATLAB

In [11]:
ms=np.linspace(1,10,10)#Create an array with 10 elements in between 1 and 10 , we no need to specify stepsize
ms

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
ms=np.linspace(1,10,5);
ms

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

# Creating array evenly spaced values within a given interval

In [15]:
ms=np.arange(1,10,1);
ms

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Note:
The interval including start but excluding stop

In [17]:
ms=np.arange(1,10,0.1);
ms

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])