# Unique Items & Count

In [19]:
a=[1,1,2,2,2,3,4,4,5,5,5,5,5];
np.unique(a)

array([1, 2, 3, 4, 5])

In [20]:
#If we want to get the count-->

In [23]:
[m,c]=np.unique(a,return_counts=True)

In [24]:
print(m);
print(c)

[1 2 3 4 5]
[2 3 1 2 5]


In [25]:
#Same concept is applicable for multidimensional array too

In [26]:
#Another way to get the count value

In [27]:
a

[1, 1, 2, 2, 2, 3, 4, 4, 5, 5, 5, 5, 5]

In [28]:
b=np.unique(a)

In [29]:
b

array([1, 2, 3, 4, 5])

In [31]:
for i in range(len(b)):
    print(sum(a==b[i]))#Simple Logic like MATLAB:-)

2
3
1
2
5


In [32]:
#This will help to calculate Mode also